# This is a TOML document

title = "repapr-sb3 config file"
algorithm = "SAC"

# 0: All / 1: learn / 2: load / 3: inherit_load
# 4: inherit_and_learn / 5: inherit_and_learn_reload
mode = 0

[input] # 入力変数
tones = 4
del_freq = 1.0
del_time = 0.001
amp = 1.0
theta_k_model = "random"
phase_value = 0.0
manual = []

[addproc] # 追加処理
rt_graph = true
notify = false

[env.param] # 環境パラメータ
continuous = true           # 連続値を使用するか
const_first_phase = true    # 1つめの位相を phase_value で固定
action_control = 0          # 0: 相対値 / 1: 絶対値
total_timesteps = 10_000    # 計算上限（継承時は無効）
max_episode_steps = 200     # 1エピソードあたりのステップ上限

[env.param.inherit]
reduction_ratio = 0.9       # 最大位相の減少倍率
stack_limit = 10            # スタック上限
init_eval = 5               # 初期学習
change_eval = 20            # 評価基準変更
n_inherit = 30              # theta_k 継承上限回数

[env.observation] # observation 設定
theta_k = false
theta_k_diff = true
ept = false
papr = true
mse = false
peaks_height = false        # calc_peaks
len_both_peaks = false      # calc_peaks

[env.reward] # reward 設定
# eval_metrics: "db"
#   eval_model: ["Raw", "Double", "Square"]
# eval_metrics: "abs"
#   eval_model: ["USo_v1", "USt_v1", "UFtSt_v1", "BSo_v1", "BSt_v1", "BFt_v1"]
# eval_metrics: "mse"
#   eval_model: ["AMSE_v0", "BMSE_v0"]
eval_metrics = "mse"
eval_model = "AMSE_v0"

[hyper] # ハイパーパラメータ
N = 16               # def: 2048 / 512 / 64
batch_size = 64      # def: 64 / 32 / 8
n_epochs = 8
alpha = 0.0003
gamma = 0.99

[output]
filepath = "repapr-sb3/out"

[output.line]
channel_token = ""
user_id = ""
